### ISSUE TITLE
Destroy connection on particular errors

### ISSUE THREAD

**Issue by jameshartig** [jackc/pgx#1803]
**Is your feature request related to a problem? Please describe.**
There are certain types of errors that might cause a developer to want to destroy a connection. Unfortunately, when you're using a pool its not easy to destroy a particular connection when an error is received. This is because the pool does:

```go
	rows, err := c.Query(ctx, sql, args...)
	if err != nil {
		c.Release()
		return errRows{err: err}, err
	}
```

So it releases the connection before the caller has a chance to assess the error.

**Describe the solution you'd like**
There are a few solutions that I see:

1. Adding a LastError to pgconn.PgConn function that returns the last `*PgError` generated from a received `*pgproto3.ErrorResponse` then a developer could setup a `AfterRelease` function that calls that function and returns false if the last error was error that should trigger a destroy. The odd part about this is that an ignored error might be returned from LastError indefinitely if another error never occurs. I'm not sure if this is a problem but it is a bit odd.

2. Adding yet another callback to a pool that gets called on errors and destroys a connection if the function returns true. This feels much more difficult since there are a lot of spots that a connection could error and we'd have to add something to all of those spots. This also feels a bit too bespoke versus the other solution.

**Describe alternatives you've considered**
I had made a map of connections -> errors and then the next time I see a connection in `AfterRelease` that had an error I wanted to destroy, I'd return false. But the way the releasing works, I'd only be able to observe the error after the connection was put back in the pool so I'd always be 1 error behind.

**Additional context**
The particular errors that we are trying to destroy based on is a shutdown error as well as an unknown session error that seems specific to yugabyte.

**Comment by jackc** [comment]
I don't think it would be too difficult to add the pool callback as far as finding all the locations. I would expect that it could be added to all the pgxpool.Conn wrapper functions. Tedious perhaps, but not too bad. The downside is it would miss any errors encountered when directly using the underlying pgx.Conn or pgconn.PgConn.

I'm open to the LastError idea. It does feel slightly inelegant, but I can't think of any better ideas. As far as LastError returning the last error indefinitely, I would expect every query to reset this value to nil.

...

Hmm... Maybe LastError is actually too little functionality. Maybe there should be some method that returns more connection state: last command tag, last error, transaction state, maybe even the parameter status map. IDK...

**Comment by jameshartig** [comment]
> Hmm... Maybe LastError is actually too little functionality. Maybe there should be some method that returns more connection state: last command tag, last error, transaction state, maybe even the parameter status map. IDK...

I like that idea, would you still expect it to clear the state every time the function is called? I was thinking of something like:

```go
type State struct {
	// ConnState is the state of the underlying connection.
	// 0 means uninitialized
	// 1 means connecting
	// 2 means closed
	// 3 means idle
	// 4 means busy
	ConnState byte

	// TxStatus is the status of the current transaction, if any. See TxStatus() for
	// definition.
	TxStatus byte

	// ParameterStatuses are the known parameters reported by the server.
	ParameterStatuses map[string]string

	// LastMessage is the last message received from the server. You MUST not modify
	// the message itself.
	LastMessage pgproto3.BackendMessage
}

// State returns the current state of the 
func (pgConn *PgConn) State() State {
	...
}
```

Thoughts?

**Comment by jackc** [comment]
I don't think that `LastMessage` would be as useful as you might hope. Even when an error is received PostgreSQL sends a `ReadyForQuery` message afterwards. That is, after a query is executed this would almost always be `ReadyForQuery`. The only exception I can think of is a fatal error which immediately kills the connection. I think `LastError` would be better.

But after further thought, now I'm second guessing myself and leaning back toward your original suggestion of simply adding a `LastError()` function. The states a user can observe a connection in are already exposed by `IsBusy()` and `IsClosed()`. `TxStatus()` already exposes the transaction status. Parameter statuses are already accessible via `ParameterStatus()` (though perhaps another function should be added to expose the keys or the whole map -- see #1814).

As far as when `LastError` would be cleared (regardless of if it is part of a `State` function or its own function) I would see it being cleared by any method that could generate or encounter an error. e.g. `Exec`, `ExecParams`, `ExecPrepared`, `CopyFrom`, etc.

Also, I would see `LastError` as explicitly being a `*pgconn.PgError` not just an `error`.

**Comment by jameshartig** [comment]
> Also, I would see LastError as explicitly being a *pgconn.PgError not just an error.

I ended up including other errors in it in case you wanted to know why the connection was closed (which might have been because of a network error).

**Comment by jameshartig** [comment]
@jackc A pgxpool issue made the `LastError` path unworkable for us. When `AfterRelease` is defined, the `Release` method is called asynchronously (see https://github.com/jackc/pgx/blob/913e4c848720ca998441e80d2224e8a084c1a442/pgxpool/conn.go#L54). This ended up causing a ~2x increase in connections when we deployed the change. Given the following pseudocode:

```go
pool.Query(...)
...
pool.Query(...)
...
```
that would have only required a single connection in the pool previously but now it requires ~2 since the first `Query()` will cause a release asynchronously which means the second `Query()` will trigger a new connection in the pool.

Changing the `AfterRelease` code to be synchronous seems like it would be a breaking change. We did try to do some workarounds with channels and notifying when `AfterRelease` was called but it still ended up racing with the underlying call to `Release`.

Instead I'd suggest we add an `OnError(*PgConn, *PgError) bool` handler to the connection's config. If this function returns false the connection will be closed immediately. The default function will return false on `FATAL` errors, which is the existing behavior. This does seem fairly pool-specific though. If you were dealing with raw connections you could check the error yourself and call `Close()` but you'd have to do that in a lot of different spots so there could still be value in this.

I opened #1826 with the above. Let me know what you think.

**Comment by jackc** [comment]
I see how `AfterRelease` being asynchronous could temporarily cause more connections to be used, though I'm not sure that is a problem. The pool still won't size still won't go over `MaxConns`

Regardless, #1826 seems like a good idea.
