### ISSUE TITLE
Support CrateDB

### ISSUE THREAD

**Issue by felixge** [jackc/pgx#320]
Hi,

thanks for this great library :).

I'm currently working on implementing [CrateDB support for influxdata/telegraf](https://github.com/influxdata/telegraf/pull/3210) and was asked by the maintainers if I could use your library instead of `lib/pq`.

Unfortunately it doesn't work because [pgx queries the postgres catalog](https://github.com/jackc/pgx/blob/master/conn.go#L387-L393) when creating a new connection, and CrateDB doesn't implement the catalog tables.

Please let me know how you feel about supporting CrateDB (or other databases pretending to be postgres on the protocol level). If you're interested, I might be able to contribute a patch. If not, feel free to simply close this issue.

Cheers
Felix

PS: I'm a huge fan of your writing. Your post [Materialized View Strategies Using PostgreSQL](https://hashrocket.com/blog/posts/materialized-view-strategies-using-postgresql) gave me the inspiration to migrate a large project (> 1 billion rows) from NoSQL to PostgreSQL. The migration was a huge success, and the analytics queries are blazing fast thanks to to some eager materialized views :).

**Comment by jackc** [comment]
I'm in favor of supporting PostgreSQL-like servers provided the changes required can be cleanly implemented. This has recently come up with RedShift SSL issues as well. In both these cases, it appears that the changes required would be localized to the connection code so it seems promising.

> PS: I'm a huge fan of your writing. Your post Materialized View Strategies Using PostgreSQL gave me the inspiration to migrate a large project (> 1 billion rows) from NoSQL to PostgreSQL. The migration was a huge success, and the analytics queries are blazing fast thanks to to some eager materialized views :).

Thanks! So glad to hear it was helpful. I might have to write an update after PG10 is released. Transition table triggers have the potential to be much more efficient for certain operations.

**Comment by jackc** [comment]
Resolved by #336.

**Comment by chetananand** [comment]
I tried the version of pgx with this patch - I still run into a similar error on https://github.com/jackc/pgx/blob/master/conn.go#L430 from initConnInfoEnumArray(). That query also is using the pg_type table without the schema pg_catalog and therefore initConnInfo() will still fail.

**Comment by felixge** [comment]
@chetananand it seems like this is a regression introduced in https://github.com/jackc/pgx/commit/ab9a1af65bf1cdaf808761cf81a310ef56795695 . The problem with my patch is that it's not included in the automatic test suite, which only runs against postgres, not CrateDB. You might want to consider using f71bf5db91970e9d5f9bfa5dfbfefb0d1e9ddcd6 for now.

@jackc would you like me to submit another patch to fix the regression?

**Comment by jackc** [comment]
> @jackc would you like me to submit another patch to fix the regression?

Sure that'd be great.

> The problem with my patch is that it's not included in the automatic test suite, which only runs against postgres, not CrateDB.

I don't know how difficult this would be to add, but some optional tests that run against CrateDB would help those of us who don't use CrateDB from breaking it in the future.

**Comment by chetananand** [comment]
Sorry for the late response @felixge - Moving to https://github.com/jackc/pgx/commit/f71bf5db91970e9d5f9bfa5dfbfefb0d1e9ddcd6 helped to get past the initial issue. Because of other unrelated limitations with CrateDB itself, I moved onto pure PostgreSQL itself. Thanks for your help.

**Comment by jackc** [comment]
> Question: Would you be okay if I move some of the bash commands from the YAML file into a dedicated bash script? This might simplify things a bit.

Sure. I don't have any strong opinions on that.

**Comment by felixge** [comment]
Closing this again as it's fixed as of https://github.com/jackc/pgx/commit/4878d9233938f8fd6d41ff03aa4ec7b020f54d01 .

PR https://github.com/jackc/pgx/pull/354 adds test coverage for CrateDB.
