### ISSUE TITLE
Error on Conn.Close() in Windows

### ISSUE THREAD

**Issue by twuillemin** [jackc/pgx#637]
### Expected Behavior
When calling _Close()_ on an open connection, the connection should be closed without raising an error. According to documentation, it is even "safe to call Close on a already closed connection."

### Current Behavior
When closing a connection, with an up to date environment on Windows, calling _Close()_ on an open connection returns an error. The error message is similar to:

``` "unable to close connection due to: read tcp [::1]:51747->[::1]:5432: wsarecv: An existing connection was forcibly closed by the remote host."```

### Steps to Reproduce
```
package main

import (
	"context"
	"log"

	"github.com/jackc/pgx/v4"
)

const testDatabaseURL = "postgresql://test:test@localhost:5432/test"

func main() {
	conn, err := pgx.Connect(context.Background(), testDatabaseURL)
	if err != nil {
		log.Fatalf("unable to open a connection due to: %v", err)
	}

	version := ""
	err = conn.QueryRow(context.Background(), "SELECT version()").Scan(&version)
	if err != nil {
		log.Fatalf("unable to execute the query due to: %v", err)
	}

	log.Printf("PostgreSQL version: %s", version)

	if err = conn.Close(context.Background()); err != nil {
		log.Fatalf("unable to close connection due to: %v", err)
	}
}
```

### Context (Environment)

- Postgresql: 12.0 / 64 bits
- Pgx: github.com/jackc/pgx/v4 v4.1.2
- Go: go version go1.13.1 windows/amd64
- Windows: Windows 10 Pro (Version 1909)

No special configuration done in PostgreSQL.

### Detailed Description
The above programming will produce the following output on Windows:
```
2019/11/15 13:08:58 PostgreSQL version: PostgreSQL 12.0, compiled by Visual C++ build 1914, 64-bit
2019/11/15 13:08:58 unable to close connection due to: read tcp [::1]:51747->[::1]:5432: wsarecv: An existing connection was forcibly closed by the remote host.
```

The issue is not present in Linux.
```
2019/11/15 12:15:01 PostgreSQL version: PostgreSQL 12.0 (Ubuntu 12.0-2.pgdg19.10+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.2.1-9ubuntu1) 9.2.1 20191008, 64-bit
```

### Preliminary investigation
The issue is raised from _pgconn.go_, function _Close(ctx context.Context)_, line 484 and following. 

An "end of connection" command is sent to postgress (`pgConn.conn.Write([]byte{'X', 0, 0, 0, 4})`). 

When sent the connection is immediately closed, according to pgadmin.

Then the connection is read (`pgConn.conn.Read(make([]byte, 1))`) up to receive an EOF error. Unfortunately, the read does no return an io.EOF error, but a net.OpError.

**Comment by jackc** [comment]
I don't have an easily accessible Windows development box so I'm shooting a little blind here but I have a few ideas.

> When calling Close() on an open connection, the connection should be closed without raising an error. According to documentation, it is even "safe to call Close on a already closed connection."

As far as it being safe to close an already closed connection, that is referring to the PgConn being closed multiple times -- not that the underlying net.Conn was closed out from under it.

```go
func (pgConn *PgConn) Close(ctx context.Context) error {
	if pgConn.status == connStatusClosed {
		return nil
	}
	pgConn.status = connStatusClose
```

But I'm not sure what to make of the `wsarecv` error. Searching for that and golang did bring up several results of odd network behavior on Windows, but nothing I could totally make sense of. Some suggestions were that the connection was being closed with a TCP RST packet instead of a FIN...

I think the next thing to investigate would be whether this is a difference with how Go handles network connections on Windows or how PostgreSQL handles network connections on Windows.

Can you try your test from Linux Go connecting to the Windows PostgreSQL server? That would tell us on which side the behavior difference is.

**Comment by twuillemin** [comment]
Hi Jack,

As suggested, I just make some tests for comparing Windows vs Linux. As before client is Windows 10 Pro (but another PC), with Go 1.13 and PGX v4.1.2

Server PG on Windows:
Windows 10 Pro
PostgreSQL 12.1
```
2019/11/17 00:30:36 PostgreSQL version: PostgreSQL 12.1, compiled by Visual C++ build 1914, 64-bit
2019/11/17 00:30:36 unable to close connection due to: read tcp 127.0.0.1:52145->127.0.0.1:5432: wsarecv: An existing connection was forcibly closed by the remote host.
```

Server PG on Linux:
Debian 10.2 - Inside VirtualBox 6.0.14
PostgreSQL 12.1
Traces:
```
2019/11/17 00:36:21 PostgreSQL version: PostgreSQL 12.1 (Debian 12.1-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
```

So, it seems that PostgreSQL is closing the connection in a subtle different way between Linux and Windows.

**Comment by jackc** [comment]
Interesting. I'm guessing that the Windows server is sending a RST instead of a FIN. Need a packet capture to know for sure. Though I'm not sure how much knowing that would help. By the time it gets to pgx it is just a net.OpError. I don't think it would be correct to treat any net.OpError the same as io.EOF.

I suppose it might also be worth considering how much meaning returning an error from Close() actually provides. Even if the Write close message or the Read until EOF fails the net connection is still closed. The only information that the error provides is a hint that the server may not consider the close to have been clean. But regardless the error is purely informational -- there is nothing the calling code can do (e.g. pgxpool ignores errors when closing connections).

**Comment by twuillemin** [comment]
Good bet about the packet. I jut ran Wireshark and there are definitely differences on the end of the connection:

Windows
![Capture Windows](https://user-images.githubusercontent.com/48868586/69004531-7d5a6880-091d-11ea-82a9-0d85b752102d.PNG)

Linux
![Capture Linux](https://user-images.githubusercontent.com/48868586/69004536-851a0d00-091d-11ea-8239-88506e2a5b64.PNG)

For Windows server, Postgres just send a RST to the client. However, for Linux server both parts of the communication send a FIN. So the root of the problem seems to be the inconsistency of Postgres for closing connection. That said, in both cases the connection is closed and we could argue that the client should adapt to both cases are they somehow valid.

At this point I see 4 solutions, neither of them perfect:

a) Leave things as is, but the clients of a Windows hosted server will have to ignore the errors from Close(). It could be added at least in the documentation. I don't really like this solution due to the fact that the clients have to adapt to something which is totally out of their control.

b) Make pgConn.Close() and so Conn.Close() not returning any kind of error. Somehow ok because there is not a lot that the client can do after requesting a close. However, in case of an error in the Write(X0004) part, the client is not informed that the connection is not properly closed.

c) take in account, that once the connection is closed, the next read can throw an io.EOF or an net.OpError depending on the server. This would lead to something like:
```golang
_, err = pgConn.conn.Read(make([]byte, 1))
if _, isNetOpp := err.(net.OpError); err != io.EOF && !isNetOpp {
	return err
}
```
Although possible, it is kind very specific and depends on Postgres implementation.

d) Simply ignore the errors from the read if any. This would lead to something like:
```golang
// Depending on the Server implementation, the Read may fail in different ways. 
// So don't bother checking it, as nothing can be done at this point.
_, _ = pgConn.conn.Read(make([]byte, 1))
```

In my opinion, solutions b (no errors from Close) or d (trap errors from Read) are probably the best options. I slightly prefer d, but that's a matter of taste.

**Comment by jackc** [comment]
I decided to mostly go with solution b. It now ignores errors from the Write and the Read. It still will return any error from the underlying net.Conn.Close (though even that is not especially actionable).

I settled on this solution after seeing that this is the behavior that the standard libpq C library uses.

```c
/*
 * sendTerminateConn
 *	 - Send a terminate message to backend.
 */
static void
sendTerminateConn(PGconn *conn)
{
	/*
	 * Note that the protocol doesn't allow us to send Terminate messages
	 * during the startup phase.
	 */
	if (conn->sock != PGINVALID_SOCKET && conn->status == CONNECTION_OK)
	{
		/*
		 * Try to send "close connection" message to backend. Ignore any
		 * error.
		 */
		pqPutMsgStart('X', false, conn);
		pqPutMsgEnd(conn);
		(void) pqFlush(conn);
	}
}
```

Fixed in https://github.com/jackc/pgconn/commit/eb81d2926b3b0519cd1fe945c2795cceeabe236c.

**Comment by iget-master** [comment]
Hi,

I'm using the latest version of this package, but seems that this issue still occurs.
